### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by wtt0525** [googlebaba/CIKM2018-AEHE#1]
您好，我对您的这篇工作比较感兴趣，想研究一下源码进一步学习。但是您提供的源码中的原文件以及数据集都是不完整的，缺少其中一些，方便的话能不能给补充完整呢？谢谢。

**Comment by googlebaba** [comment]
重新整理了代码和数据：链接：https://pan.baidu.com/s/1EiPmrDMugIwC3tRBoYLf6Q 
提取码：7hu7

**Comment by googlebaba** [comment]
> 您好，我对您的这篇工作比较感兴趣，想研究一下源码进一步学习。但是您提供的源码中的原文件以及数据集都是不完整的，缺少其中一些，方便的话能不能给补充完整呢？谢谢。
重新整理了代码和数据：
链接：https://pan.baidu.com/s/1EiPmrDMugIwC3tRBoYLf6Q 
提取码：7hu7

**Comment by wtt0525** [comment]
哇，这么快就收到了回复，非常感谢




------------------ 原始邮件 ------------------
发件人: "googlebaba"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 晚上9:22
收件人: "googlebaba/CIKM2018-AEHE"<CIKM2018-AEHE@noreply.github.com>;
抄送: "巴黎没有塔℃"<1416562377@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [googlebaba/CIKM2018-AEHE] About the code (#1)



 
您好，我对您的这篇工作比较感兴趣，想研究一下源码进一步学习。但是您提供的源码中的原文件以及数据集都是不完整的，缺少其中一些，方便的话能不能给补充完整呢？谢谢。
 重新整理了代码和数据：
 链接：https://pan.baidu.com/s/1EiPmrDMugIwC3tRBoYLf6Q
 提取码：7hu7
